objave = {
    "objava1" : {
        "img" : "fet.webp",
        "naslov" : "FET OSCILOSKOPSKA SONDA ZA VIŠE FREKVENCIJE",
        "tekst" : "To je problem koji muči elektronske inženjere od kada su prvi elektroni navučeni duž žice: da mjerni instrumenti sami mogu poremetiti rad kola.<br> Stariji multimetri su, na primjer, imali dovoljno niske impedancije da povuku vrijednosti otpornika, tako da naši multimetri danas imaju FET ulaze visoke impedancije.<br><br> [Christoph] se suočio sa svojom sondom za osciloskop, njen ulazni kapacitet je bio dovoljno visok da stavi neprihvatljivo opterećenje na kristalni oscilator i zaustavi njegovo oscilovanje.<br> Tako je napravio FET ulaznu sondu za više RF frekvencije, a njena konstrukcija je pristupačan pogled na dizajn širokopojasne RF instrumentacije.<br><br> Kolo je vrlo jednostavno i koristi FET sa dvostrukim vratima, ali interesovanje dolazi za PCB i ekran može biti dizajniran da osigura dobre RF performanse. Konzerve u prodaji imaju četiri strane, tako da je jedan zid limenke morao biti uklonjen da bi se prilagodio strujnom krugu. Krajnji rezultat je sićušna PCB sa minijaturnim koaksijalnim konektorima za napajanje i signal, za koje je utvrđeno da kada su okarakterisani imaju propusni opseg od 1,3 GHz i vrlo nisku ulaznu kapacitivnost. Ako vam je jezik RF dizajna stran, možemo li preporučiti govor [Michaela Ossmanna] na Superkonferenciji prije nekoliko godina."
    },
    "objava2" : {
        "img" : "temperatura.webp",
        "naslov" : "TOPLOTNI MOTOR VISOKIH TEMPERATURA POSTIŽE 40% EFIKASNOSTI",
        "tekst" : "Ljudi stvaraju mnogo otpadne topline. Logično je da postoji želja da se ta toplota pretvori u upotrebljivu energiju. Problem je u efikasnosti.<br> Istraživači sa MIT-a i Nacionalne laboratorije za obnovljivu energiju najavili su novi pretvarač toplote za koji tvrde da ima efikasnost od 40%. Naravno, postoji kvaka. Raspon temperature za uređaje počinje od 1.900 °C.<br><br> Termofotonaponske ćelije su tandem uređaji s dvije ćelije spojene na jednoj podlozi. Svaka ćelija je višestruki sloj vrlo tankih i pomalo egzotičnih materijala.<br> Dakle, ovo vjerovatno nije nešto što ćete uskoro popločati u svom podrumu osim ako već ne proizvodite IC-ove dolje. Čini se da je tajna u više slojeva, uključujući reflektirajući, koji sve propuštene fotone šalje nazad kroz stog.<br><br> Rad je prilično gust, ali postoji sažetak nedjeljnog dodatka na stranici MIT-a. Korištenje skladištenja topline dovodi do mogućnosti stvaranja toplinskih baterija, više ili manje, i iskorištavanja onoga što bi inače bila rasipanje energije. U posljednje vrijeme primjećujemo veliki interes za crpljenje energije iz vrućih cijevi. Sve te tehnike koje smo vidjeli oslanjaju se na neke vrste egzotičnih materijala."
    },
    "objava3" : {
        "img" : "biciklo.webp",
        "naslov" : "HOVERBIKE PRETVARA HOVERBOARD U BICIKLO",
        "tekst" : "Hoverboardi su bili popularan trend među mladima i publikom prije nekoliko godina, a sada kada je moda uveliko zamrla, ima ih mnogo neiskorištenih u ormarima i podrumima širom svijeta. To samo znači mogućnosti da se dijelovi ovih jedinstvenih transportnih uređaja ugrade u druge konstrukcije.<br><br> Praktičniji način transporta je bicikl, a ova konstrukcija sakuplja većinu dijelova sa hoverboarda kako bi se običan bicikl pretvorio u zippy ebike. Ova konstrukcija bicikla počinje s okvirom za brdski bicikl i dijelovi sa hoverboarda dodaju mu se dio po dio.<br><br> Dva motora su montirana na okvir i pokreću prednji prsten lanca bicikla, omogućavajući mu da i dalje koristi prednosti pogonskog sklopa bicikla. Baterijski paketi iz dva hoverboarda su spojeni u jednu bateriju koja biciklu daje skromnih 6-10 km dometa ovisno o upotrebi.<br> Ali pravi dragulj ove izrade je uzimanje žiroskopske kontrolne ploče sa hoverboarda i pretvaranje, uz pomoć Arduino Due-a, u ebike kontroler. Na kraju će se dodati baterija kako bi se biciklu pružio udobniji domet, ali za sada cijenimo domišljatost koja je bila potrebna da se kontroler sa hoverboarda prilagodi u kontroler za ebike zajedno sa asistencijom za gas i pedalu. Za ostale kućne predmete pretvorene u ebicikle, svakako pogledajte jedan od naših omiljenih baziranih na motoru za pranje rublja: ciklus centrifuge."
    },
    "objava4" : {
        "img" : "jabuke.webp",
        "naslov" : "NAPUNITE SVOJ APPLE PROIZVOD JABUKAMA",
        "tekst" : "Kada razmišljate o etanolu, možda ćete o njemu razmišljati kao o vrsti alkohola, a ne o samom alkoholu. Međutim, u stvarnosti, to je primarni sastojak napitaka za odrasle. Što znači da su ljudi postali prilično dobri u pravljenju, kao što mi to radimo već duže vrijeme.<br><br> Imajući ovo na umu, [Sam Barker] je odlučio da napravi etanol od jabuka za pogon malog motora za punjenje svog telefona. Koraci za pravljenje čistog etanola prilično su slični pravljenju alkoholnog jabukovača. [Samov] prijatelj imao je voćnjak i višak jabuka, pa ih je [Sam] skuhao i spremio kašu u vrčeve.<br><br> Dodao je aktivirani suvi kvasac kako bi započeo proces fermentacije. Suva brava je omogućila da plin CO2 koji se stvarao pobjegne. Tokom nekoliko sedmica, kvasac je sav šećer pretvorio u etanol i plin. U međuvremenu, [Sam] je nabavio motornu testeru i prilagodio motor da radi na etanol, jer etanol treba da radi bogatije od benzina.<br><br> Video ispod pauze priča priču. Sa svojom otopinom od samo 15% etanola, trebao ga je destilirati da bi dobio čisti etanol za rad motora. Uz malo mahanja rukama zbog zakona Ujedinjenog Kraljevstva, [Sam] je ubrzo dobio 94% otopinu etanola.<br> Sljedeći korak je bio korištenje molekularnog sita, koje je apsorbiralo vodu, ali ne i etanol. Pričvrstio je motor i generator na staru dasku za rezanje i [Sam] je bio spreman za prvi test.<br> Fino podešavanje desnog gasa i prigušivača je potrajalo, ali [Sam] je to stalno išlo kada je naleteo na prepreku;<br> telefon se nije punio. Upalio je motor i njegov mali regulator punjenja je eksplodirao. Njegove multimetarske sonde su bile unatrag kada je izmjerio generator i davao je negativan napon. Sa zamijenjenom pločom, telefon je napunjen. Ali [Sam] je ponekad vidio preko 50 volti kako izlazi iz motora. Dakle, kao i većina ovdje u Hackadayu, želio je vidjeti koliko brzo/visoko/daleko može ići. Ovo je na kraju spržilo motor. Ako ste zainteresirani za modificiranje generatora tako da odgovaraju vašim specifičnim potrebama za gorivom, imamo generatore koji rade na prirodni plin, amonijak, pa čak i na vaše noge."
    },
    "objava5" : {
        "img" : "obradjivaczvuka.webp",
        "naslov" : "OBRADA ZVUKA SA RP2040",
        "tekst" : "Raspberry Pi, iako je prvo bio zamišljen kao jeftin računar na jednoj ploči za upotrebu u obrazovanju, sada je sveprisutan u zajednicama elektronike.<br> Njegova niska cijena, kao i Linux platforma i pristupačan GPIO čine ga korisnim na mnogim mjestima van učionice. Ali, ako želite da napustite jednostavnost korišćenja u korist još niže cene, Raspberry Pi fondacija to omogućava i sa RP2040 čipom, koji se obično nalazi na Pico-u.<br><br> [Jason] nam pokazuje jedan način da iskoristimo ovaj moćni čip tako što ćemo ga staviti u ploču za obradu digitalnog audio signala. Iako su razvojne ploče dostupne za ovaj čip, [Jason] se umjesto toga odlučio za prilagođenu PCB koju je sam dizajnirao i uključuje integrirano pojačalo za slušalice i 3,5 mm audio priključke.<br><br> Da bi obavio stvarni DSP rad, RP2040 čip koristi tri 12-bitna ADC kanala i 16 PWM kanala kojima se može upravljati. Platforma je također opremljena TLV320AIC3254 kodekom iz Texas Instrumentsa. Uz sve ovo zajedno, on ima funkcionalnu platformu otvorenog koda koju naziva DS-Pi. [Jason] je napravio ovo kao platformu za gitarske efekte i kao prilagodljiv model za gitarsko pojačalo, ali sa platformom koja je kompatibilna sa Arduino i prilično laka za programiranje može se koristiti za bilo šta što uključuje druge vrste muzike ili audio obrade , poput ove specijalizovane MIDI kompatibilne platforme za gitarske efekte koja je izgrađena oko istog procesora."
    },
    "objava6" : {
        "img" : "gladijator.webp",
        "naslov" : "MERENJE ELEKTROMAGNETNIH POLJA SA SAMO ARDUINOM I KOMADOM ŽICE",
        "tekst" : "Problemi s elektromagnetnim smetnjama mogu biti prava glavobolja za otklanjanje grešaka. Ako trebate dokazati što uzrokuje usporavanje vašeg WiFi-a ili opadanje digitalnog TV signala, tada vam mogućnost mjerenja elektromagnetnih polja (EMF) može biti od velike pomoći.<br> Profesionalna oprema je često vrlo skupa, ali sami napraviti EMF detektor nije čak ni tako teško: samo pogledajte praktičan ručni detektor elektromagnetnog polja Arduino stručnjaka [Mirka Pavleskog].<br><br> Osnovna ideja je prilično jednostavna: povežite antenu direktno na Arduino analogni ulaz i vizualizirajte signal koji mjeri.<br> Budući da je ulaz ADC-a visoke impedancije, on je vrlo osjetljiv na sve lutajuće struje koje pokupi antena. U stvari, toliko osjetljiv, da je potreban otpornik od nekoliko mega-oma prema masi kako bi se senzor spriječio da se aktivira na bilo koju vrstu nasumične buke. [Mirko] je taj otpor napravio podesivim sa nekoliko dugmića i prekidača tako da se detektor može koristiti i u tihim i u bučnim okruženjima.<br><br> Omogućavanje pouzdanog rada čitavog uređaja bila je zanimljiva vježba u elektromagnetskom inženjerstvu: u prvih nekoliko iteracija, detektor bi aktivirao vlastite LED diode i zujalicu, hvatajući se u beskrajnu petlju. [Mirko] je ovo riješio tako što je Arduino stavio u zatvorenu, uzemljenu metalnu kutiju iz koje vire samo potrebne žice. Dizajn antene je uglavnom bio zasnovan na pokušajima i greškama; trenutna postavka sa komadom aluminijumskog lima veličine 7 cm x 3 cm izgleda dobro radi. Iako ovo nije kalibrirani instrument profesionalnog nivoa, trebao bi biti od koristi za pronalaženje izvora smetnji, ili čak jednostavno za lociranje skrivenih kablova za napajanje. Ovo možete gledati kao napredniju verziju [Mirkovog] Junk Box EMF detektora; ako imate drugi Arduino koji leži uokolo, možete ga koristiti za stvaranje smetnji."
    },
    "objava7" : {
        "img" : "misterijaTV.webp",
        "naslov" : "MOŽETE LI POMOĆI U RJEŠAVANJU MISTERIJE OVOG TV-a iz 1930-ih?",
        "tekst" : "Prije 84 godine, tinejdžer je napravio televizor u podrumu u Hamondu u Indijani. Tinejdžer je bio radio-amater, [John Anderson W9YEI], a budući da je to bilo kasnih 1930-ih, set je bio jedinstvene konstrukcije - jedan od rijetkih postojećih napravljenih da hvata jedan od prvih eksperimentalnih TV predajnika u to vrijeme, W9XZV u Chicagu. Znamo za njega zbog spominjanja u radio emisiji iz 1973. godine, i zato što je to dalo primamljiv opis, zainteresovao je [Bill Meara, N2CQR].<br><br> On prati sve detalje koje može pronaći kroz niz postova na blogu, i iako je pronašao mnogo fascinantnih stvari o ranim TV prijemnicima, moli za još. Bilo koji televizor iz kasnih 30-ih bio je vrijedan pažnje, pa postoji li još neko ko ima priču o ovome? The set itself was described as an aluminium chassis with a tiny 1″ CRT, something which for a 1930s experimenter would have been an expensive and exotic part. He’s found details of a contemporary set published in a magazine, and looking at its circuit diagram we were immediately struck by how relatively simple the circuit of an electrostatically-deflected TV is. Its tuned radio frequency (TRF) radio front end is definitely archaic, but something that probably made some sense in 1939 when there was only a single channel to be received. We hope that [Bill] manages to turn up more information."
    },
    "objava8" : {
        "img" : "kosilicabraaaca.webp",
        "naslov" : "KOSILICA-ČETVEROTOČKAŠ",
        "tekst" : "Prva faza projekta uključuje uklanjanje svih hardvera vezanih za košnju, jer očigledno nećete kositi travu dok gurate brzinom od 80 km/h.<br> Ovo istovremeno štedi težinu i uklanja mnoge mehaničke komplikacije koje bi bile na putu daljnje modifikacije. Međutim, to također ostavlja kosilicu nepokretnom, jer više nema veze između motora i mjenjača.<br><br> Na njegovo mjesto ugrađuje se gotovi komplet pretvarača obrtnog momenta koji koristi kvačilo s kontinuirano varijabilnim prijenosom (CVT). CVT tehnologija omogućava da se omjer prijenosa automatski prilagodi broju okretaja motora zahvaljujući remenicama koje mijenjaju svoju veličinu ovisno o tome koliko brzo se okreću.<br> To je veliko poboljšanje u odnosu na sistem koji je prvobitno izvukao, iako kao što možete očekivati, njegovo postavljanje u kosilicu zahtijevalo je određeni rad. Posljednji korak je bio povlačenje stare remenice s mjenjača i zamjena s onom koja je manja od polovine originalne veličine."
    },
    "objava9" : {
        "img" : "sahatcina.jpg",
        "naslov" : "SAHAT-KULA",
        "tekst" : "Ovo je sat baziran na Attiny 816 / 1616, dijelom napravljen od PCB-a, a dijelom slobodnog oblika. Sa pomakom od manje od jedne sekunde dnevno (kako pišem) dovoljno je precizan da se može pouzdano koristiti. Posjeduje sedmosegmentni displej koji pokreću dva registra pomeranja, piezo souder, fotodiodni krug za prilagođavanje zatamnjenja ekrana ambijentalnom svijetlu, a koristi kristal sata da obezbijedi otkucavanje sata. Koristi USB C da obezbijedi struju i ima rezervnu bateriju, tako da se zadržava vrijeme kada je napajanje izgubljeno (ovaj dio još nije implementiran)."
    },
    "objava10" : {
        "img" : "doktorsam.webp",
        "naslov" : "DIŠITE LAKŠE UZ OVU OGRLICU SA LED SENZOROM",
        "tekst" : "Kada pravite nosive i svjetleće uređaje, ponekad je blistava duginska animacija sve što vam treba. Međutim, ponekad je dobro otići malo dalje i napraviti ovu impresivnu ogrlicu koja služi za informiranje o kvaliteti lokalnog zraka.<br> Ogrlica se sastoji od serije Neopixel LED traka, smještenih u urednom 3D štampanom kućištu napravljenom od fleksibilnog filamenta.<br> Spoj u obliku lastinog repa čini stavljanje i skidanje ogrlice lakim. TinyPico V2, baziran na ESP32, vodi emisiju, jer je vrlo mali i stoga savršen za nosivu aplikaciju. USB power bank obezbjeđuje napajanje mikrokontroleru i LED diodama. TinyPico koristi svoju WiFi vezu za upite serveru koji ima podatke o kvaliteti zraka iz zasebne senzorske jedinice.<br><br> Ogrlica standardno prikazuje animaciju mirnog disanja u hladnim tonovima. Međutim, kada se kvalitet zraka pogorša, on pokazuje toplije i toplije boje na oštriji i življi način. Nije uvijek lako napraviti projekte koji su i funkcionalni i udobni za nošenje, ali ovaj funkcionira na oba aspekta. I 3D fajlovi za ogrlicu i kod firmvera mikrokontrolera uključeni su u GitHub repo za one koji žele da zarone u sitnice."
    }
};